language: perl
perl:
  - "5.20"

env:
  global:
    - COVERAGE=1

before_install:

  # Set git config values that mod/tests will look for.
  # The build will short-circuit if `git` returns non-zero.
  - |
    : # configure git for tests
    gc () { git config --global "$1" "$2"; }
    gc github.user travis
    gc user.name   travis
    gc user.email  travis@example.com

  # eval $(curl https://travis-perl.github.io/init) --auto
  - |
    : # travis helpers
    helper_dir="$(mktemp -d -t travis-perl-helpers-XXXXXX)";
    git clone --depth 1 git://github.com/travis-perl/helpers "$helper_dir";
    source "$helper_dir/init"

    build-perl

    depdir="$(mktemp -d -t authordeps-XXXXXX)";

    INSPECTOR=Dist::Zilla::Config::BundleInspector
    BUNDLE=Dist::Zilla::PluginBundle::Author::MJGARDNER

    # Install author deps once to get bundle inspector, roles, etc.
    $helper_dir/bin/cpan-install `dzil authordeps | grep -v $BUNDLE`

    perl -Ilib -M$INSPECTOR -e "print $INSPECTOR->new(bundle_class => q[$BUNDLE])->ini_string" >> $depdir/dist.ini

    # Now install the deps the inpector told us about.
    $helper_dir/bin/cpan-install `dzil authordeps --root $depdir`

    setup-auto

# Use newer travis infrastructure.
sudo: false
